"""Shifted split producer + variant metadata (item 3 of the spec).

A :class:`ShiftVariant` wraps a shifted :class:`Split` together with the
metadata every variant must carry. The clean split is never modified: each
variant is generated by copying it and applying one shift axis at one severity.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from tice.datasets.registry import Split
from tice.seed import derive_seed
from tice.shifts.generators import get_shift


def _train_test_duplicate_rate(split: Split) -> float:
    X_train, X_test = split.X_train, split.X_test
    if len(X_test) == 0:
        return 0.0
    train_keys = set(map(tuple, X_train.to_numpy().tolist()))
    hits = sum(1 for row in X_test.to_numpy().tolist() if tuple(row) in train_keys)
    return float(hits / len(X_test))


def leakage_risk_level(split: Split) -> str:
    """Coarse contamination proxy from the train/test exact-duplicate rate."""
    rate = _train_test_duplicate_rate(split)
    if rate > 0.05:
        return "high"
    if rate > 0.0:
        return "medium"
    return "low"


def check_clean_split(split: Split) -> bool:
    """Basic sanity gate on the *clean* split.

    Passes when both sides are non-empty, every clean class is represented in
    train, and there is no gross train/test contamination.
    """
    if len(split.X_train) == 0 or len(split.X_test) == 0:
        return False
    train_classes = set(split.y_train.unique().tolist())
    if not set(split.classes).issubset(train_classes):
        return False
    if _train_test_duplicate_rate(split) > 0.05:
        return False
    return True


@dataclass(frozen=True)
class ShiftVariant:
    """A shifted split plus its provenance metadata."""

    dataset_id: str
    shift_axis: str
    shift_lambda: float
    seed: int
    split_policy: str
    clean_split_passed: bool
    leakage_risk_level: str
    split: Split = field(repr=False)

    def metadata(self) -> dict:
        return {
            "dataset_id": self.dataset_id,
            "shift_axis": self.shift_axis,
            "shift_lambda": self.shift_lambda,
            "seed": self.seed,
            "split_policy": self.split_policy,
            "clean_split_passed": self.clean_split_passed,
            "leakage_risk_level": self.leakage_risk_level,
        }


def make_shift_variant(
    clean_split: Split,
    axis: str,
    lam: float,
    *,
    base_seed: int,
    clean_split_passed: bool | None = None,
) -> ShiftVariant:
    """Produce one shifted variant of ``clean_split`` for ``axis`` at severity ``lam``."""
    shift = get_shift(axis)
    seed = derive_seed(base_seed, clean_split.dataset_id, axis, lam)
    shifted = shift.apply(clean_split, lam, base_seed)
    if clean_split_passed is None:
        clean_split_passed = check_clean_split(clean_split)
    return ShiftVariant(
        dataset_id=clean_split.dataset_id,
        shift_axis=axis,
        shift_lambda=float(lam),
        seed=seed,
        split_policy=shift.split_policy,
        clean_split_passed=clean_split_passed,
        leakage_risk_level=leakage_risk_level(shifted),
        split=shifted,
    )
